theme: jekyll-theme-slate
gems:
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-redirect-from
title: "Immune Response Template"
description: "annotation and numerical description of immune response in humans"
show_downloads: false
demo_path: online
google_analytics: UA-86578005-2
yandex_metrika: 38306160
twitter:
  username: insysbio
  