theme: jekyll-theme-slate
gems:
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-redirect-from
title: "Immune Response Template"
description: "Annotation and numerical description of immune response in humans"
logo: /images/logo_isb.png
show_downloads: false
demo_path: online
google_analytics: UA-86578005-2
yandex_metrika: 38306160
facebook:
  app_id: 1234
twitter:
  username: insysbio
social:
  name: InSysBio
  links:
    - https://www.facebook.com/insysbio
    - https://www.linkedin.com/insysbio
    - https://github.com/insysbio
    - https://twitter.com/insysbio
    - https://insysbio.ru/en
defaults:
  - scope:
      path: ""
    values:
      image: /images/general_view.png
